### ISSUE TITLE
module fails on default hornetq settings

### ISSUE THREAD

**Issue by deepfry0** [rhtconsulting/puppet-jboss_admin#102]
If you have hornetq configurations in the standalone instance, json parsing fails because the default remoteconnectionfactory has retry-interval-multiplier in unquoted strings

```
"RemoteConnectionFactory" => {
                            "auto-group" => false,
                            "block-on-acknowledge" => true,
                           
                             "retry-interval-multiplier" => big decimal 1.0,
}
```

This will show up when we are trying to prefetch all cli resources

**Comment by deepfry0** [comment]
This seems to be a bug introduced in the module code after September 2015. Something to do with the commits for how resources are prefetched and cached.

**Comment by itewk** [comment]
@deepfry0 checkout https://github.com/rhtconsulting/puppet-jboss_admin/commit/87a28f761b1585c1b56857f85b968bae6cddfca5

The fix for this will need to be in the same place. Feel up to the challenge of creating a patch and testing?

**Comment by itewk** [comment]
@deepfry0 and you are correct, this would have bee introduced by the code pre-fetching everything.

**Comment by deepfry0** [comment]
Fix is being tested in house. Will submit a patch in the next couple of days.
For reference, this is the addition to json_string - gsub(/ => big decimal/, ': ')

**Comment by itewk** [comment]
Merged.
