### ISSUE TITLE
Could not prefetch jboss_resource provider 'cli': 399: unexpected token at 'timeout: failed to run command '/usr/share/jbossas/bin/jboss-cli.sh': No such file or directory]'

### ISSUE THREAD

**Issue by itewk** [rhtconsulting/puppet-jboss_admin#80]
I have no clue why but in my lab environment whenever I create a new VM on the first puppet run I get this error:

```
Could not prefetch jboss_resource provider 'cli': 399: unexpected token at 'timeout: failed to run command '/usr/share/jbossas/bin/jboss-cli.sh': No such file or directory]'
```

On the second puppet run everything works fine.

it is important to note on the first puppet run Jboss has not installed itself yet. On the second puppet run though JBoss has still not yet installed because the first puppet run failed, but on the second run puppet installs jboss and then jboss_admin does its thing without error.

For some reason on the first puppet run all of my attempts at forceing puppet to install jboss and start it before doing any jboss_admin work is just ignored. But then on the second puppet run it works.

@cpitman  any smart ideas?

**Comment by ldomb** [comment]
That might be because the dependencies (require, include, contain) are not
written correctly.

**Comment by itewk** [comment]
@idomb,

Iv checked and rechecked and checked again my ordering and it is all correct. I think for some reason the prefetch is ignoring the order, but that is just a hypothesis.

**Comment by itewk** [comment]
I no longer see this. Closing.
