### ISSUE TITLE
all jboss_admin::resource::* types should pass their name as the name to the wrapped jboss_resource type

### ISSUE THREAD

**Issue by itewk** [rhtconsulting/puppet-jboss_admin#87]
Currently it is impossible to configure two JBoss EAP servers with the jboss_admin module because the cli_path is passed as the name to the jboss_resource type by all of the jboss_admin::resources::* types. Instead the name field of the jboss_admin::resources::* types should be passed to the wrapped jboss_resource so that conflicts can be avoided.

**Comment by itewk** [comment]
@simhpl

If you want to try to do this you need to look at lib/tasks/manifest.erb, lines 64-68. That is the template used to generate all of the jboss_resources.

You then need to manually update all of the resources in internal/custom_resource, because they are all over rides for the autogenerated types where needed.

You then need to run the "rake resource:generate" command to generate all the new resources.

Then test.

Some more details on the generation can be found in the README.md in the Generating Resources section. Also see the Developer Setup section.

**Comment by simhpl** [comment]
@itewk 
Great, thanks. I will look into it.
Changing the provider will also be necessary, right? I mean the jboss_resource provider? or the jboss_resource type as well?

**Comment by itewk** [comment]
@simhpl 

the jboss_resource type already has an "address" field. You should be able to update the template to pass the jboss_admin::resource::*::cli_path to the jboss_resource::address field and then pass the jboss_admin::resource::*::name as the jobss_resource::name to prevent the duplicate resources assuming the user passes unique names to jboss_admin::resource::*

**Comment by itewk** [comment]
merged into master.
