### ISSUE TITLE
path_generator#root_dump_position needs to deal with values wrapped in quotes

### ISSUE THREAD

**Issue by itewk** [rhtconsulting/puppet-jboss_admin#96]
path_generator#root_dump_position can not currently handle the following CLI address since the value is wrapped in quotes.
```
CLI address: /subsystem=naming/binding="java:/comp/env/MY_BINDING_0"
```

Function needs to be updated to deal with this use case.

**Comment by itewk** [comment]
@ramius345 can you review this change please.

**Comment by ramius345** [comment]
approved.

**Comment by itewk** [comment]
Merged into master.
