### ISSUE TITLE
retries should be handled at the execute_cli level for cli command execution

### ISSUE THREAD

**Issue by ramius345** [rhtconsulting/puppet-jboss_admin#97]
There is code scattered about the three types jboss_resource, jboss_exec, and jboss_batch that all attempt retries of various cli commands.  This causes unexpected cli timeouts to pop up in our overnight testing.  Refactoring the code to handle retries (with some default settings) inside of execute_cli should help alleviate this problem.

**Comment by itewk** [comment]
approved after change to remove unnecessary "require 'pp'"

**Comment by itewk** [comment]
merged into master
